" GUI Specific settings

if has("gui_macvim")

  set fuoptions=maxvert,maxhorz " fullscreen options (MacVim only), resized window when changed to fullscreen
  set guifont=Monaco:h12
  set guioptions-=T  " remove toolbar
  set guioptions+=c  " use text console instead of modal popup for confirmation dialogues
  set guioptions-=r  " remove right scroll bar
  set guioptions-=L  " remove left scroll bar when there is a vertically split window
  set guicursor=a:blinkon0
  set lcs=tab:¬¬,trail:·    " (lcs) strings used in 'list' mode to show hidden characters (default=eol:$)
  set listchars+=precedes:→ " (lcs) when 'nowrap', character to indicate that line continues off the page
  set listchars+=extends:←

  " Unmap Apple+T and Shift+Apple+T
  macmenu &File.Open\ Tab\.\.\. key=<nop>

  " NerdTree
  nnoremap <D-e> :NERDTreeToggle<CR>

  " Tab navigation like FF and TM
  nnoremap <D-M-right> :tabnext<CR>
  nnoremap <D-M-left> :tabprev<CR>

elseif has("gui_gtk2")

  set guifont=Monaco
  set guioptions-=T  " remove toolbar

end

set anti " Antialias font

" Default size of window
set columns=120
set lines=50

" Tab headings
set gtl=%t gtt=%F
