" Pathogen set up
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on

source $HOME/.vim/vimrc_settings
source $HOME/.vim/vimrc_functions
source $HOME/.vim/vimrc_commands
source $HOME/.vim/vimrc_mappings
source $HOME/.vim/vimrc_autocmds

if &loadplugins
  source $HOME/.vim/vimrc_plugins
endif
